- type: job
  id: CETownfolk
  setPreference: true
  name: ce-job-name-townfolk
  description: ce-job-desc-townfolk
  playTimeTracker: CEJobTownfolk
  startingGear: CETownfolkGear
  icon: CEJobIconTownfolk
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

- type: startingGear
  id: CETownfolkGear
  equipment:
    belt: CEWalletFilledTownfolk

- type: entity
  id: CEWalletFilledTownfolk
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10
