- type: job
  id: CETavernmaster
  setPreference: true
  name: ce-job-name-tavernmaster
  description: ce-job-desc-tavernmaster
  playTimeTracker: CEJobTavernmaster
  startingGear: CETavernmasterGear
  icon: CEJobIconTavernmaster
  supervisors: ce-job-supervisors-empire
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: true
  weight: 2

- type: startingGear
  id: CETavernmasterGear
  equipment:
    keys: CEKeyRingTavernmaster
    belt: CEWalletFilledTavernmaster


- type: entity
  id: CEWalletFilledTavernmaster
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEKeyRingTavernmaster
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyTavernHall
    - id: CEKeyTavernStaff
    - id: CEKeyTavernHeadRoom
