- type: antag
  id: CEVampire
  name: ce-roles-antag-vampire-name
  antagonist: true
  setPreference: true
  objective: ce-roles-antag-vampire-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 7200 # 2h
  #guides: TODO
